"""unikalny slot serii

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-04 03:35:46.568627
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Wyścig sprzed tej migracji mógł zostawić duplikaty (ten sam slot serii
    # utworzony dwa razy przez równoległe żądania). Bez ich usunięcia
    # constraint się nie założy. Zostawiamy wystąpienie o najniższym id —
    # jest najstarsze, więc to na nie wskazują ewentualne prośby o przełożenie.
    op.execute(
        """
        DELETE FROM lessons
        WHERE series_id IS NOT NULL
          AND origin_date IS NOT NULL
          AND id NOT IN (
              SELECT MIN(id) FROM lessons
              WHERE series_id IS NOT NULL AND origin_date IS NOT NULL
              GROUP BY series_id, origin_date
          )
        """
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_lessons_series_origin', ['series_id', 'origin_date'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lessons_series_origin', type_='unique')

    # ### end Alembic commands ###
