"""opis zmiany

Revision ID: e99594cc564b
Revises: 0002
Create Date: 2026-08-03 22:57:12.512026
"""
from alembic import op
import sqlalchemy as sa


revision = 'e99594cc564b'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_series_assigned_tutor_id'), ['assigned_tutor_id'], unique=False)
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_tutor_id'], ['id'])

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_assigned_tutor_id'), ['assigned_tutor_id'], unique=False)
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_tutor_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_logins', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_logins')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lessons_assigned_tutor_id'))

    with op.batch_alter_table('lesson_series', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lesson_series_assigned_tutor_id'))

    # ### end Alembic commands ###
